apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: default

data:
  DB_WRITER_HOST: "main-aurora-cluster.cluster-csujc6lew69u.us-east-1.rds.amazonaws.com"
  DB_READER_HOST: "main-aurora-cluster.cluster-ro-csujc6lew69u.us-east-1.rds.amazonaws.com"

  DB_PORT: "3306"
  DB_NAME: "crm_db"

  PORT: "3001"
  CORS_ORIGIN: "*"
