apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: default

data:
  DB_WRITER_HOST: "${WRITER}"
  DB_READER_HOST: "${READER}"

  DB_PORT: "3306"
  DB_NAME: "crm_db"

  PORT: "3001"
  CORS_ORIGIN: "*"
